export const templateVars = {
  attributeFragments: 'attributeFragments',
  attributes: 'attributes',
  blocksPerInstance: 'blocksPerInstance',
  instanceBlockCount: 'instanceBlockCount',
  instanceDataBinaryTree: 'instanceDataBinaryTree',
  instanceDataRetrieval: 'instanceDataRetrieval',
  instanceDestructuring: 'instanceDestructuring',
  instanceFragments: 'instanceFragments',
  instanceUniformDeclarations: 'instanceUniformDeclarations',
  layerUniforms: 'layerUniforms',
  picking: 'picking',
  projectionMethods: 'projectionMethods',
  shader: 'shader',
  shaderInput: 'shaderInput',
  vertexAttributes: 'vertexAttributes',
};
