import {
  AnchorType,
  AutoEasingMethod,
  BasicCameraController,
  ChartCamera,
  createLayer,
  EventManager,
  InstanceProvider,
  LabelInstance,
  LabelLayer,
  LayerInitializer
} from "src";
import { BaseExample, TestResourceKeys } from "./base-example";

export class FontEngineGlyphControl extends BaseExample {
  makeController(
    defaultCamera: ChartCamera,
    _testCamera: ChartCamera,
    viewName: string
  ): EventManager {
    return new BasicCameraController({
      camera: defaultCamera,
      startView: viewName,
      wheelShouldScroll: true
    });
  }

  makeLayer(
    scene: string,
    resource: TestResourceKeys,
    provider: InstanceProvider<LabelInstance>
  ): LayerInitializer {
    return createLayer(LabelLayer, {
      animate: {
        offset: AutoEasingMethod.easeInOutCubic(2000),
        color: AutoEasingMethod.easeInOutCubic(2000),
        origin: AutoEasingMethod.easeInOutCubic(2000)
      },
      resourceKey: resource.font,
      data: provider,
      key: "font-engine-glyph-control",
      scene
    });
  }

  makeProvider(): InstanceProvider<LabelInstance> {
    const bounds = this.surface.getViewSize(this.view);
    const provider = new InstanceProvider<LabelInstance>();
    if (!bounds) return provider;

    const lines = story.split("\n");
    let i = 0;

    for (; i < lines.length; ++i) {
      if (lines[i]) {
        provider.add(
          new LabelInstance({
            anchor: {
              padding: 0,
              type: AnchorType.MiddleLeft
            },
            color: [1, 1, 1, 1],
            fontSize: 12,
            text: lines[i],
            origin: [20, 14 + i * 14],
            maxWidth: bounds.width - 40
          })
        );
      }
    }

    for (const iMax = i + 200; i < iMax; ++i) {
      const length = Math.ceil(Math.random() * 10);
      const sentence = [];

      for (let k = 0; k < length; ++k) {
        sentence.push(words[Math.floor(Math.random() * words.length)]);
      }

      provider.add(
        new LabelInstance({
          anchor: {
            padding: 0,
            type: AnchorType.MiddleLeft
          },
          color: [1, 1, 1, 1],
          fontSize: 11,
          text: sentence.join(" "),
          origin: [20, 14 + i * 14],
          maxWidth: bounds.width - 40
        })
      );
    }

    return provider;
  }
}

const story = `
Tom Sawyer


CHAPTER I
"TOM!"
No answer.

"TOM!"

No answer.

"What's gone with that boy, I wonder? You TOM!"

No answer.

The old lady pulled her spectacles down and looked over them about the room; then she put them up and looked out under them. She seldom or never looked THROUGH them for so small a thing as a boy; they were her state pair, the pride of her heart, and were built for "style," not service -- she could have seen through a pair of stove-lids just as well. She looked perplexed for a moment, and then said, not fiercely, but still loud enough for the furniture to hear:

"Well, I lay if I get hold of you I'll --"

She did not finish, for by this time she was bending down and punching under the bed with the broom, and so she needed breath to punctuate the punches with. She resurrected nothing but the cat.

"I never did see the beat of that boy!"

She went to the open door and stood in it and looked out among the tomato vines and "jimpson" weeds that constituted the garden. No Tom. So she lifted up her voice at an angle calculated for distance and shouted:

"Y-o-u-u TOM!"

There was a slight noise behind her and she turned just in time to seize a small boy by the slack of his roundabout and arrest his flight.

"There! I might 'a' thought of that closet. What you been doing in there?"

"Nothing."

"Nothing! Look at your hands. And look at your mouth. What IS that truck?"

"I don't know, aunt."

"Well, I know. It's jam -- that's what it is. Forty times I've said if you didn't let that jam alone I'd skin you. Hand me that switch."

The switch hovered in the air -- the peril was des- perate --

"My! Look behind you, aunt!"

The old lady whirled round, and snatched her skirts out of danger. The lad fled on the instant, scrambled up the high board-fence, and disappeared over it.

His aunt Polly stood surprised a moment, and then broke into a gentle laugh.

"Hang the boy, can't I never learn anything? Ain't he played me tricks enough like that for me to be look- ing out for him by this time? But old fools is the big- gest fools there is. Can't learn an old dog new tricks, as the saying is. But my goodness, he never plays them alike, two days, and how is a body to know what's coming? He 'pears to know just how long he can torment me before I get my dander up, and he knows if he can make out to put me off for a minute or make me laugh, it's all down again and I can't hit him a lick. I ain't doing my duty by that boy, and that's the Lord's truth, goodness knows. Spare the rod and spile the child, as the Good Book says. I'm a laying up sin and suffering for us both, I know. He's full of the Old Scratch, but laws-a-me! he's my own dead sister's boy, poor thing, and I ain't got the heart to lash him, some- how. Every time I let him off, my conscience does hurt me so, and every time I hit him my old heart most breaks. Well-a-well, man that is born of woman is of few days and full of trouble, as the Scripture says, and I reckon it's so. He'll play hookey this evening, * and [* Southwestern for "afternoon"] I'll just be obleeged to make him work, to-morrow, to punish him. It's mighty hard to make him work Saturdays, when all the boys is having holiday, but he hates work more than he hates anything else, and I've GOT to do some of my duty by him, or I'll be the ruination of the child."

Tom did play hookey, and he had a very good time. He got back home barely in season to help Jim, the small colored boy, saw next-day's wood and split the kindlings before supper -- at least he was there in time to tell his adventures to Jim while Jim did three-fourths of the work. Tom's younger brother (or rather half-brother) Sid was already through with his part of the work (picking up chips), for he was a quiet boy, and had no adventurous, trouble- some ways.

While Tom was eating his supper, and stealing sugar as opportunity offered, Aunt Polly asked him questions that were full of guile, and very deep -- for she wanted to trap him into damaging revealments. Like many other simple-hearted souls, it was her pet vanity to believe she was endowed with a talent for dark and mysterious diplomacy, and she loved to con- template her most transparent devices as marvels of low cunning. Said she:

"Tom, it was middling warm in school, warn't it?"

"Yes'm."

"Powerful warm, warn't it?"

"Yes'm."

"Didn't you want to go in a-swimming, Tom?"

A bit of a scare shot through Tom -- a touch of uncomfortable suspicion. He searched Aunt Polly's face, but it told him nothing. So he said:

"No'm -- well, not very much."

The old lady reached out her hand and felt Tom's shirt, and said:

"But you ain't too warm now, though." And it flattered her to reflect that she had discovered that the shirt was dry without anybody knowing that that was what she had in her mind. But in spite of her, Tom knew where the wind lay, now. So he forestalled what might be the next move:

"Some of us pumped on our heads -- mine's damp yet. See?"

Aunt Polly was vexed to think she had overlooked that bit of circumstantial evidence, and missed a trick. Then she had a new inspiration:

"Tom, you didn't have to undo your shirt collar where I sewed it, to pump on your head, did you? Unbutton your jacket!"

The trouble vanished out of Tom's face. He opened his jacket. His shirt collar was securely sewed.

"Bother! Well, go 'long with you. I'd made sure you'd played hookey and been a-swimming. But I forgive ye, Tom. I reckon you're a kind of a singed cat, as the saying is -- better'n you look. THIS time."

She was half sorry her sagacity had miscarried, and half glad that Tom had stumbled into obedient con- duct for once.

But Sidney said:

"Well, now, if I didn't think you sewed his collar with white thread, but it's black."

"Why, I did sew it with white! Tom!"

But Tom did not wait for the rest. As he went out at the door he said:

"Siddy, I'll lick you for that."

In a safe place Tom examined two large needles which were thrust into the lapels of his jacket, and had thread bound about them -- one needle carried white thread and the other black. He said:

"She'd never noticed if it hadn't been for Sid. Confound it! sometimes she sews it with white, and sometimes she sews it with black. I wish to gee- miny she'd stick to one or t'other -- I can't keep the run of 'em. But I bet you I'll lam Sid for that. I'll learn him!"

He was not the Model Boy of the village. He knew the model boy very well though -- and loathed him.

Within two minutes, or even less, he had forgotten all his troubles. Not because his troubles were one whit less heavy and bitter to him than a man's are to a man, but because a new and powerful interest bore them down and drove them out of his mind for the time -- just as men's misfortunes are forgotten in the excite- ment of new enterprises. This new interest was a valued novelty in whistling, which he had just acquired from a negro, and he was suffering to practise it un- disturbed. It consisted in a peculiar bird-like turn, a sort of liquid warble, produced by touching the tongue to the roof of the mouth at short intervals in the midst of the music -- the reader probably remembers how to do it, if he has ever been a boy. Diligence and attention soon gave him the knack of it, and he strode down the street with his mouth full of harmony and his soul full of gratitude. He felt much as an astronomer feels who has discovered a new planet -- no doubt, as far as strong, deep, unalloyed pleasure is concerned, the advantage was with the boy, not the astronomer.

The summer evenings were long. It was not dark, yet. Presently Tom checked his whistle. A stranger was before him -- a boy a shade larger than himself. A new-comer of any age or either sex was an im- pressive curiosity in the poor little shabby village of St. Petersburg. This boy was well dressed, too -- well dressed on a week-day. This was simply as- tounding. His cap was a dainty thing, his close- buttoned blue cloth roundabout was new and natty, and so were his pantaloons. He had shoes on -- and it was only Friday. He even wore a necktie, a bright bit of ribbon. He had a citified air about him that ate into Tom's vitals. The more Tom stared at the splendid marvel, the higher he turned up his nose at his finery and the shabbier and shabbier his own outfit seemed to him to grow. Neither boy spoke. If one moved, the other moved -- but only sidewise, in a circle; they kept face to face and eye to eye all the time. Finally Tom said:

"I can lick you!"

"I'd like to see you try it."

"Well, I can do it."

"No you can't, either."

"Yes I can."

"No you can't."

"I can."

"You can't."

"Can!"

"Can't!"

An uncomfortable pause. Then Tom said:

"What's your name?"

"'Tisn't any of your business, maybe."

"Well I 'low I'll MAKE it my business."

"Well why don't you?"

"If you say much, I will."

"Much -- much -- MUCH. There now."

"Oh, you think you're mighty smart, DON'T you? I could lick you with one hand tied behind me, if I wanted to."

"Well why don't you DO it? You SAY you can do it."

"Well I WILL, if you fool with me."

"Oh yes -- I've seen whole families in the same fix."

"Smarty! You think you're SOME, now, DON'T you? Oh, what a hat!"

"You can lump that hat if you don't like it. I dare you to knock it off -- and anybody that'll take a dare will suck eggs."

"You're a liar!"

"You're another."

"You're a fighting liar and dasn't take it up."

"Aw -- take a walk!"

"Say -- if you give me much more of your sass I'll take and bounce a rock off'n your head."

"Oh, of COURSE you will."

"Well I WILL."

"Well why don't you DO it then? What do you keep SAYING you will for? Why don't you DO it? It's because you're afraid."

"I AIN'T afraid."

"You are."

"I ain't."

"You are."

Another pause, and more eying and sidling around each other. Presently they were shoulder to shoulder. Tom said:

"Get away from here!"

"Go away yourself!"

"I won't."

"I won't either."

So they stood, each with a foot placed at an angle as a brace, and both shoving with might and main, and glowering at each other with hate. But neither could get an advantage. After struggling till both were hot and flushed, each relaxed his strain with watchful caution, and Tom said:

"You're a coward and a pup. I'll tell my big brother on you, and he can thrash you with his little finger, and I'll make him do it, too."

"What do I care for your big brother? I've got a brother that's bigger than he is -- and what's more, he can throw him over that fence, too." [Both brothers were imaginary.]

"That's a lie."

"YOUR saying so don't make it so."

Tom drew a line in the dust with his big toe, and said:

"I dare you to step over that, and I'll lick you till you can't stand up. Anybody that'll take a dare will steal sheep."

The new boy stepped over promptly, and said:

"Now you said you'd do it, now let's see you do it."

"Don't you crowd me now; you better look out."

"Well, you SAID you'd do it -- why don't you do it?"

"By jingo! for two cents I WILL do it."

The new boy took two broad coppers out of his pocket and held them out with derision. Tom struck them to the ground. In an instant both boys were rolling and tumbling in the dirt, gripped together like cats; and for the space of a minute they tugged and tore at each other's hair and clothes, punched and scratched each other's nose, and covered themselves with dust and glory. Presently the confusion took form, and through the fog of battle Tom appeared, seated astride the new boy, and pounding him with his fists. "Holler 'nuff!" said he.

The boy only struggled to free himself. He was crying -- mainly from rage.

"Holler 'nuff!" -- and the pounding went on.

At last the stranger got out a smothered "'Nuff!" and Tom let him up and said:

"Now that'll learn you. Better look out who you're fooling with next time."

The new boy went off brushing the dust from his clothes, sobbing, snuffling, and occasionally looking back and shaking his head and threatening what he would do to Tom the "next time he caught him out." To which Tom responded with jeers, and started off in high feather, and as soon as his back was turned the new boy snatched up a stone, threw it and hit him be- tween the shoulders and then turned tail and ran like an antelope. Tom chased the traitor home, and thus found out where he lived. He then held a position at the gate for some time, daring the enemy to come out- side, but the enemy only made faces at him through the window and declined. At last the enemy's mother appeared, and called Tom a bad, vicious, vulgar child, and ordered him away. So he went away; but he said he "'lowed" to "lay" for that boy.

He got home pretty late that night, and when he climbed cautiously in at the window, he uncovered an ambuscade, in the person of his aunt; and when she saw the state his clothes were in her resolution to turn his Saturday holiday into captivity at hard labor became adamantine in its firmness.
`;

const words = [
  "misogyny",
  "fatiguing",
  "refillable",
  "devocalised",
  "outpreening",
  "regales",
  "relishing",
  "enjamb",
  "mardiest",
  "unseasonablenesses",
  "tanghinin",
  "ethnolinguists",
  "stackup",
  "kidnapers",
  "acetonemias",
  "selfwards",
  "mischief",
  "granitoid",
  "noetic",
  "somatotonias",
  "tunicae",
  "dreamily",
  "satinpods",
  "gridlocked",
  "ravager",
  "congou",
  "fumiest",
  "geminal",
  "televangelists",
  "tiltings",
  "eutropous",
  "parapenting",
  "epigrammatising",
  "restricted",
  "rapines",
  "vocalions",
  "crinoid",
  "maledicts",
  "whooting",
  "abrins",
  "fenlands",
  "blabbing",
  "fuehrer",
  "weatherglasses",
  "disproperty",
  "damp",
  "ghaut",
  "declinable",
  "doweling",
  "pining",
  "refel",
  "satay",
  "grampuses",
  "calves",
  "horizontally",
  "dos",
  "spammers",
  "lightings",
  "litters",
  "outgain",
  "immolated",
  "sents",
  "spitfires",
  "outloves",
  "suspenseful",
  "deration",
  "incapsulating",
  "erinite",
  "nowcastings",
  "padronism",
  "circumscribes",
  "islomania",
  "pyogenic",
  "empoverished",
  "zebrines",
  "oodlins",
  "beneficial",
  "ballow",
  "nerve",
  "hydrocracking",
  "patronnes",
  "hymns",
  "crenellated",
  "didakeis",
  "hypallactic",
  "gearshifts",
  "fathomlessnesses",
  "convergent",
  "mortices",
  "wanton",
  "pressurises",
  "shunning",
  "shemozzling",
  "lodgepoles",
  "brothy",
  "serial",
  "sails",
  "unacted",
  "acaridans",
  "quadrivalents",
  "sectarianisms",
  "wasp",
  "limitable",
  "muraenids",
  "damaged",
  "gladiuses",
  "checkmark",
  "chiltepins",
  "asperous",
  "castral",
  "superpatriotic",
  "recharters",
  "squattocracy",
  "vellum",
  "allomerous",
  "tweest",
  "gibbered",
  "cathetuses",
  "nonsmokers",
  "rhombi",
  "homestalls",
  "insolidities",
  "misroutes",
  "quillets",
  "topophilia",
  "monologise",
  "jaspery",
  "bulbiferous",
  "landlordisms",
  "phyllotaxy",
  "apices",
  "parging",
  "lunting",
  "successionally",
  "cranky",
  "macrozamia",
  "splattering",
  "dodo",
  "outdazzles",
  "myriapodous",
  "stobs",
  "trailbaston",
  "schoolchild",
  "executorship",
  "larnakes",
  "underquoted",
  "dadahs",
  "nonfeminist",
  "whish",
  "ileitides",
  "weathercasters",
  "futurition",
  "significancies",
  "genuflector",
  "metatarsi",
  "necklace",
  "drying",
  "quotha",
  "happily",
  "satchelful",
  "frothing",
  "morainal",
  "kabaka",
  "sorceress",
  "vanda",
  "blowtorch",
  "freighters",
  "croft",
  "veracities",
  "suffixions",
  "unsinew",
  "phenomenizing",
  "politick",
  "axite",
  "cotemporary",
  "oceanid",
  "astrict",
  "fitches",
  "toccatella",
  "self",
  "manures",
  "succinite",
  "oxygenisers",
  "halters",
  "anastrozole",
  "dreadlocks",
  "larrupers",
  "talcking",
  "indigenize",
  "awaiter",
  "cockinesses",
  "defraudments",
  "baccoes",
  "bambino",
  "epigenesists",
  "deerstalkings",
  "parietal",
  "flouts",
  "uglier",
  "fundraises",
  "hygrometers",
  "absorbency",
  "facinorousness",
  "nurserymen",
  "kawanatanga",
  "calamancoes",
  "unshrouds",
  "dialyzable",
  "gazogenes",
  "strayved",
  "dragrope",
  "syllabical",
  "nominees",
  "rust",
  "shoat",
  "interpluvial",
  "subarctics",
  "detectophones",
  "spheroidizes",
  "forcer",
  "wienie",
  "antiderivative",
  "dipshit",
  "idealized",
  "skewback",
  "unfumed",
  "pikings",
  "homs",
  "trimers",
  "aida",
  "rebroadcast",
  "tantalizes",
  "championing",
  "bursters",
  "grysely",
  "beylik",
  "succubi",
  "counterculture",
  "epexegetic",
  "tarings",
  "panzer",
  "screenager",
  "sexton",
  "otioseness",
  "cite",
  "reengages",
  "burglarize",
  "outjested",
  "fortissimo",
  "chiffonniers",
  "uncrates",
  "desulfurization",
  "frugally",
  "tumbles",
  "mucronate",
  "dioristical",
  "multicourses",
  "balefulness",
  "shalwar",
  "alembicated",
  "jeon",
  "balladmonger",
  "samming",
  "importunes",
  "zoogamies",
  "optimised",
  "pluripotent",
  "ruedas",
  "pee",
  "insultable",
  "hypermodern",
  "manches",
  "mesquine",
  "hazan",
  "dreadnoughts",
  "energy",
  "encephala",
  "germanising",
  "vauted",
  "unwiser",
  "mufflered",
  "bicameralists",
  "gloop",
  "pulvinate",
  "turbidimetry",
  "grantsmanships",
  "spliff",
  "swingingly",
  "phene",
  "opposable",
  "dispatchers",
  "footslogged",
  "galvanism",
  "longe",
  "fairnyticles",
  "schoolmates",
  "soapboxes",
  "watercraft",
  "vowelized",
  "chaologies",
  "vasectomize",
  "weeting",
  "peggings",
  "bosques",
  "exosmic",
  "supremacisms",
  "lagering",
  "shampooer",
  "gunsmiths",
  "stenned",
  "taikos",
  "concierge",
  "unmistrustful",
  "besighed",
  "reticent",
  "tetradrachm",
  "hilloa",
  "patricians",
  "tannoy",
  "gravidly",
  "multivocals",
  "appraisees",
  "hides",
  "verdins",
  "necessitative",
  "overlying",
  "discoloration",
  "unstrengthened",
  "classworks",
  "scrooging",
  "foliage",
  "maser",
  "malfed",
  "unrelieved",
  "wained",
  "gaminesses",
  "guerillaisms",
  "prating",
  "throughfare",
  "sublibrarian",
  "metazoal",
  "stead",
  "danegelts",
  "laxism",
  "hiatus",
  "exegetically",
  "triscele",
  "panhandling",
  "bladdery",
  "rebooking",
  "perianth",
  "crenellation",
  "meshuga",
  "litigable",
  "decreases",
  "traveled",
  "trackside",
  "farcers",
  "couturiers",
  "employing",
  "afterheat",
  "unpitted",
  "nectariferous",
  "toerag",
  "subfusk",
  "syllabary",
  "patness",
  "apperceive",
  "nonstories",
  "buddles",
  "guaiocum",
  "bluecoats",
  "sanctifiers",
  "niff",
  "pernoctated",
  "mangoldwurzels",
  "unobservances",
  "imperturbations",
  "glarinesses",
  "effectuating",
  "panicked",
  "fadaise",
  "gadis",
  "undertint",
  "shaker",
  "skeeters",
  "polygamized",
  "euphemising",
  "hackbolts",
  "readjusting",
  "unattractively",
  "clovis",
  "slayings",
  "smickers",
  "anonymousnesses",
  "incalculable",
  "candescent",
  "reestablishing",
  "strunt",
  "aquatinted",
  "pneumatology",
  "restlessness",
  "pochay",
  "aluminise",
  "kirbehs",
  "uglied",
  "cires",
  "gamekeeping",
  "outdazzled",
  "potamogetons",
  "champak",
  "gorditas",
  "ultracentrifugal",
  "cagynesses",
  "transfiguring",
  "shirtier",
  "kibbitzed",
  "outpreen",
  "columnea",
  "bundobust",
  "kissings",
  "logographical",
  "ravishingly",
  "repellently",
  "antimale",
  "pooves",
  "phospholipase",
  "accidentals",
  "gabionnade",
  "pitchiest",
  "allovers",
  "focalization",
  "spadroon",
  "lapsing",
  "pickax",
  "photographist",
  "toxicology",
  "bummalotis",
  "nutate",
  "footrope",
  "concomitancies",
  "venereans",
  "flatways",
  "panelised",
  "eavesdrops",
  "mazes",
  "bilby",
  "phosphatidylethanolamines",
  "tubulate",
  "dendrochronological",
  "payroll",
  "monotone",
  "sycophants",
  "hoof",
  "sass",
  "disquietnesses",
  "scrotum",
  "noninstallment",
  "pornotopia",
  "ebonized",
  "sutras",
  "preventions",
  "underloads",
  "stownding",
  "accelerated",
  "disusages",
  "twite",
  "sideropenias",
  "earshots",
  "treehoppers",
  "marocains",
  "disarraying",
  "kidnaps",
  "gnomon",
  "pampean",
  "derationed",
  "unquestioningly",
  "dogeys",
  "frusta",
  "beggaries",
  "reptile",
  "nundine",
  "overstaining",
  "condensibility",
  "kittlest",
  "greywacke",
  "dredgers",
  "courbettes",
  "altezzas",
  "desertified",
  "carbonizes",
  "ballonets",
  "dorkier",
  "slabstones",
  "etheromanias",
  "flavourers",
  "forgivers",
  "reclusivenesses",
  "telangiectasis",
  "nicher",
  "downslope",
  "tisicks",
  "outsavors",
  "gamme",
  "cruciate",
  "perished",
  "reinnervates",
  "cogently",
  "tallets",
  "stripteasers",
  "biramose",
  "hessonites",
  "toteable",
  "twofers",
  "millings",
  "upclimbing",
  "cresta",
  "clutchy",
  "milestones",
  "coccidioidomycosis",
  "blamefully",
  "ren",
  "stockishly",
  "redfoot",
  "theralite",
  "buntlines",
  "leveled",
  "brachet",
  "rearranger",
  "unstabler",
  "frees",
  "claymores",
  "cleverly",
  "mepacrines",
  "biparty",
  "corymbed",
  "exhibiter",
  "caries",
  "steepens",
  "remobilize",
  "manliness",
  "cystinoses",
  "mockado",
  "referrers",
  "chill",
  "stayer",
  "olfaction",
  "minimaxed",
  "destabilizer",
  "fiaschi",
  "supportances",
  "satangs",
  "saddles",
  "shootdowns",
  "communality",
  "tote",
  "warners",
  "geophyte",
  "monopolizes",
  "scrubbiest",
  "emmarbled",
  "confluent",
  "scaleni",
  "tripartitions",
  "unlethal",
  "nondiscriminatory",
  "overscutched",
  "microfilmer",
  "bladding",
  "quat",
  "depasture",
  "cogencies",
  "pretrims",
  "meniscoid",
  "geognosts",
  "uncirculated",
  "pseudoscalars",
  "arete",
  "gingkoes",
  "forelock",
  "crofters",
  "heteropterous",
  "instantaneously",
  "earache",
  "overstretched",
  "curpels",
  "almucantars",
  "blog",
  "hypernovae",
  "ineffaceable",
  "waved",
  "homogenization",
  "gracefully",
  "norias",
  "palaestras",
  "polemicised",
  "fixatif",
  "cardioid",
  "tolbooth",
  "condoled",
  "disqualifies",
  "briner",
  "internationalising",
  "forsterites",
  "scarpa",
  "gusseting",
  "bimorphemic",
  "recovered",
  "emancipationist",
  "squabbing",
  "expense",
  "phylloclades",
  "prostrated",
  "thionyls",
  "knowingnesses",
  "acidophilous",
  "dodgeries",
  "transgressively",
  "nesher",
  "overdevelopments",
  "travesty",
  "confederated",
  "monogynous",
  "suprarenal",
  "unravelment",
  "thermoremanences",
  "accorders",
  "cooter",
  "nonclassrooms",
  "moneymakings",
  "anarchised",
  "outdress",
  "sacralizations",
  "counterevidence",
  "erecter",
  "escapism",
  "raia",
  "daubings",
  "rebate",
  "gjus",
  "spenses",
  "enables",
  "fibrolite",
  "tripersonalist",
  "cabdrivers",
  "tutty",
  "zebrawoods",
  "deepnesses",
  "twistings",
  "panfried",
  "paraphasia",
  "balsamy",
  "thump",
  "preife",
  "mycophagous",
  "parchmentises",
  "benefactory",
  "eclogites",
  "renforces",
  "cellarists",
  "lewisia",
  "grope",
  "facinerious",
  "recalesced",
  "recreance",
  "unactive",
  "appendix",
  "repolling",
  "hyperrationalities",
  "gynecocracy",
  "warerooms",
  "pixelations",
  "underbuilds",
  "heave",
  "transliterated",
  "equalization",
  "slimily",
  "tsarist",
  "phonetisations",
  "revise",
  "unenvious",
  "voicemails",
  "batholith",
  "monogenistic",
  "claspings",
  "songstresses",
  "monologised",
  "massagist",
  "drinking",
  "disaventrous",
  "prills",
  "anting",
  "conquered",
  "mantissas",
  "outspelled",
  "primmers",
  "technomusic",
  "cobbleries",
  "nidifications",
  "besports",
  "olecranon",
  "vicennial",
  "tickliest",
  "charpoys",
  "cercaria",
  "radialia",
  "dunlin",
  "prysing",
  "toreutic",
  "signified",
  "unsteadiest",
  "greengrocers",
  "denuclearize",
  "blamefulness",
  "succose",
  "teleshopped",
  "patriarchy",
  "blueings",
  "homoeomorphous",
  "curator",
  "freshing",
  "inrushings",
  "greaves",
  "counterintelligence",
  "tinselling",
  "seaware",
  "gutsful",
  "exsecting",
  "renormalized",
  "reopeners",
  "abscessed",
  "hydrazoic",
  "wisent",
  "suppressor",
  "herisse",
  "amaranth",
  "dibromide",
  "thrills",
  "rewakened",
  "solutions",
  "cursoriness",
  "reesty",
  "emplastron",
  "repleads",
  "multidomain",
  "classroom",
  "misquoting",
  "photorealism",
  "sigillarians",
  "rowlocks",
  "unwieldy",
  "spancel",
  "frolics",
  "muskie",
  "euge",
  "textual",
  "grecianized",
  "leptotenes",
  "crofter",
  "carlish",
  "outtops",
  "midcults",
  "stations",
  "gamesman",
  "gnotobiotically",
  "jibbooms",
  "splintlike",
  "hoplitic",
  "differentiabilities",
  "tapus",
  "paltered",
  "roods",
  "unawarely",
  "footwells",
  "rhinocerotic",
  "hostly",
  "moxa",
  "antimacho",
  "approximations",
  "cagework",
  "accrescent",
  "skriked",
  "undervotes",
  "morgays",
  "deliberateness",
  "choppily",
  "kahunas",
  "arguable",
  "bumpiness",
  "loath",
  "umbonation",
  "dawns",
  "frutescence",
  "chiefer",
  "labefactations",
  "unreliability",
  "verves",
  "flouse",
  "soddiest",
  "jiggles",
  "roentgenologist",
  "tuftaffetas",
  "suppressed",
  "philopoenas",
  "spirography",
  "superstore",
  "paleobiological",
  "nonfunctioning",
  "overachieved",
  "nutritions",
  "kiddied",
  "misacceptations",
  "gonophs",
  "veilleuses",
  "dormered",
  "lionheartedness",
  "decarboxylases",
  "maisonnettes",
  "callipashes",
  "videographers",
  "delayed",
  "ahuru",
  "ineligibilities",
  "uncoalesces",
  "neuromata",
  "streel",
  "fundraise",
  "blower",
  "whipping",
  "sonsier",
  "reproaches",
  "counterworld",
  "friand",
  "pooper",
  "milkworts",
  "scintillon",
  "pottymouth",
  "hypercharging",
  "egestion",
  "glonoin",
  "tubbier",
  "faints",
  "copataine",
  "aerobicise",
  "neckerchief",
  "bivalence",
  "macromere",
  "cockchafers",
  "prearranges",
  "duress",
  "telesms",
  "empuse",
  "fluffy",
  "sulfated",
  "haleru",
  "wholeness",
  "masoned",
  "threnodists",
  "kloochmen",
  "clostridia",
  "preternaturalnesses",
  "radioiodines",
  "horticulturist",
  "tireling",
  "pension",
  "unsystematised",
  "lampyrids",
  "odisms",
  "reimpositions",
  "hijacked",
  "effrontery",
  "virilization",
  "isohydric",
  "isleless",
  "sclerotisations",
  "oka",
  "irrespectively",
  "assotting",
  "dispensed",
  "greenbacker",
  "harpsichords",
  "crawlingly",
  "ranshackles",
  "cheaped",
  "irremovability",
  "foxing",
  "storyette",
  "goaled",
  "lobose",
  "inflatables",
  "drovers",
  "shapeliest",
  "fatting",
  "necrotroph",
  "chaumer",
  "odontoblast",
  "hong",
  "oximeters",
  "palkis",
  "cowfeeders",
  "aboriginally",
  "arsenopyrites",
  "calcar",
  "etiologies",
  "quadrennial",
  "disfigurement",
  "pries",
  "sunbather",
  "fuchsite",
  "antimodernist",
  "loot",
  "dehypnotising",
  "remoisten",
  "philippinas",
  "ichnographic",
  "suffocatingly",
  "unextinguished",
  "persicarias",
  "trabeculate",
  "compounders",
  "immensities",
  "nightside",
  "summiteer",
  "tigerishnesses",
  "agitations",
  "nonpractising",
  "iatrogenicity",
  "bottarga",
  "survey",
  "nosheries",
  "apperceives",
  "positons",
  "deprive",
  "temperate",
  "unction",
  "paraphraxis",
  "recursivenesses",
  "blunderbuss",
  "gobstoppers",
  "seneschal",
  "bioprospectings",
  "sarcinas",
  "slapstick",
  "superjumbo",
  "fuehrer",
  "sentience",
  "intermarrying",
  "dicting",
  "keynoter",
  "rubbery",
  "outchided",
  "comply",
  "embourgeoising",
  "nebulousnesses",
  "capsular",
  "freedwoman",
  "inspirative",
  "limitation",
  "petroglyphies",
  "ionophores",
  "gardenfuls",
  "andrologist",
  "shampoo",
  "gauleiters",
  "boilerplates",
  "unbeholden",
  "raffish",
  "coolness",
  "swingisms",
  "obstetrician",
  "burganets",
  "jinkers",
  "systemised",
  "syver",
  "terts",
  "trampette",
  "algolagnists",
  "radioimmunoassay",
  "mesodermic",
  "rubbly",
  "sapling",
  "scrimpness",
  "overtrusts",
  "chimichanga",
  "amalgamates",
  "washerman",
  "disuse",
  "uric",
  "primatologists",
  "salinometric",
  "tractate",
  "congiary",
  "verite",
  "vectorizations",
  "openhandednesses",
  "pencilings",
  "nirvanic",
  "restrooms",
  "negrophilisms",
  "dreggiest",
  "sphericality",
  "limestone",
  "overpeoples",
  "singularize",
  "ledger",
  "bipartition",
  "countermotion",
  "kinematograph",
  "tenanted",
  "serrulation",
  "heteronomies",
  "retunds",
  "prestidigitations",
  "pinnock",
  "unwarie",
  "faradise",
  "eyas",
  "bounteousness",
  "bioclimatic",
  "clots",
  "impostrous",
  "constructor",
  "depauperize",
  "cobalts",
  "circularisation",
  "pater",
  "rescored",
  "silicates",
  "knawe",
  "nonsecretors",
  "basket",
  "redactional",
  "embittering",
  "creaghs",
  "expertisms",
  "rajahships",
  "grisliest",
  "appeases",
  "reindustrialized",
  "lurings",
  "meoued",
  "foreslows",
  "pucelles",
  "omniform",
  "catacaustics",
  "intervillage",
  "butted",
  "firming",
  "minoritaire",
  "raiyat",
  "verbalizes",
  "debasing",
  "genetic",
  "minke",
  "stative",
  "chalcedonyx",
  "acromions",
  "toolheads",
  "misemployment",
  "gland",
  "foreigner",
  "gitterning",
  "barrener",
  "neosoul",
  "moneylender",
  "bozo",
  "unpure",
  "psychiater",
  "abutter",
  "renaissance",
  "kudus",
  "preservable",
  "jamlike",
  "malodour",
  "nought",
  "babblier",
  "millidegrees",
  "dentural",
  "ladieswear",
  "wintergreens",
  "bladings",
  "nonresidency",
  "ancestral",
  "decriminalizations",
  "encamp",
  "redetermines",
  "semiautomatically",
  "platitudinizers",
  "rhombuses",
  "unpretending",
  "uptimes",
  "pterylosis",
  "thence",
  "unmannerly",
  "aport",
  "overcrowding",
  "afterglow",
  "potoo",
  "reprobing",
  "cudgelers",
  "unrestfulnesses",
  "fedayee",
  "myologists",
  "octants",
  "snakiest",
  "raucously",
  "typey",
  "horselaughs",
  "oligodendroglia",
  "magnetized",
  "cascades",
  "staircase",
  "garcons",
  "danelaw",
  "phaenogam",
  "potstone",
  "helplessness",
  "amounting",
  "dorsoventrally",
  "obeyed",
  "fortieth",
  "surras",
  "sculpturesque",
  "lockstitch",
  "divulgates",
  "rostellum",
  "douanes",
  "achage",
  "deforciant",
  "intermaxillary",
  "supersensitive",
  "sheeled",
  "confederate",
  "extinguishes",
  "abet",
  "millilitre",
  "overinterpretations",
  "cystines",
  "unwarped",
  "vitalization",
  "monsterings",
  "ochreae",
  "trailers",
  "tebbads",
  "refencing",
  "dicker",
  "toothful",
  "einkorn",
  "fulminous",
  "commissarial",
  "micrometeoroid",
  "meddler",
  "envisioned",
  "caracara",
  "hydrogenize",
  "entamebae",
  "illiquidity",
  "carburized",
  "pandaring",
  "fareboxes",
  "hegumenies",
  "conferees",
  "aeroplankton",
  "hygrodeiks",
  "titanate",
  "gest",
  "flooding",
  "courtezans",
  "intercooler",
  "joneses",
  "toffishnesses",
  "screwier",
  "overreach",
  "dystocia",
  "krumkake",
  "spleenwort",
  "aulnagers",
  "duddier",
  "exuviate",
  "stub",
  "aals",
  "depressible",
  "previsors",
  "traumatism",
  "catharizing",
  "nonpayments",
  "tunicin",
  "overexpanding",
  "brainiac",
  "gular",
  "decrepitnesses",
  "bridled",
  "dearths",
  "monomaniacal",
  "sidedress",
  "jurants",
  "chikaras",
  "caponiere",
  "upliftings",
  "caducities",
  "cocurator",
  "rompish",
  "inhales",
  "strinkled",
  "herblike",
  "steamrollers",
  "dungeons",
  "reticulately",
  "lowsing",
  "gymnosophs",
  "baying",
  "teleutosporic",
  "conjugalities",
  "fossick",
  "goopier",
  "stalkless",
  "graphitise",
  "toxemia",
  "cereous",
  "muskox",
  "misconjecturing",
  "cycadaceous",
  "citriculturist",
  "dispauperizes",
  "protolanguage",
  "magus",
  "apportion",
  "substanceless",
  "heartrending",
  "mopanes",
  "darrayning",
  "sclerotins",
  "resinously",
  "bitchiest",
  "hairsplitting",
  "malarial",
  "botanicas",
  "oatcakes",
  "lapful",
  "botanical",
  "dormouse",
  "bentier",
  "ensample",
  "versed",
  "umbrated",
  "myriadth",
  "narwhales",
  "jellyfish",
  "ribbings",
  "stumpage",
  "prognose",
  "unsuspended",
  "limepits",
  "soured",
  "ecotoxic",
  "pylon",
  "forsythia",
  "flickertail",
  "shutdowns",
  "stucco",
  "malpractices",
  "mujahidin",
  "sidewards",
  "condemners",
  "ollav",
  "folliculitides",
  "groolier",
  "diuron",
  "vodcasted",
  "whicker",
  "rewet",
  "weight",
  "telophase",
  "ribaudred",
  "piecrusts",
  "turlough",
  "chastised",
  "provostries",
  "flamboyant",
  "unendangered",
  "veges",
  "alumna",
  "abomination",
  "streamier",
  "hispidity",
  "submergement",
  "tortillon",
  "stewy",
  "branned",
  "orgy",
  "revets",
  "whitier",
  "forestial",
  "moles",
  "placidest",
  "disjointedness",
  "nauplii",
  "infantile",
  "beefcake",
  "process",
  "stimulaters",
  "glucan",
  "optionals",
  "unanswerabilities",
  "bullions",
  "lientery",
  "oversides",
  "semiquaver",
  "agueweeds",
  "cerebriform",
  "unbedding",
  "lovey",
  "christophany",
  "gummoses",
  "tabrere",
  "determinatively",
  "vetted",
  "cadie",
  "curialistic",
  "tuart",
  "atropous",
  "stagecoaching",
  "archbishoprics",
  "musicalities",
  "meetings",
  "philoxenia",
  "ginks",
  "gull",
  "curfs",
  "empiricists",
  "bravo",
  "tenebrific",
  "magnanimities",
  "pozz",
  "trample",
  "doomsmen",
  "linguistically",
  "squailer",
  "frikkadel",
  "sharn",
  "quahog",
  "misbestowals",
  "generalises",
  "rancher",
  "agitates",
  "samiest",
  "obstreperousnesses",
  "soporiferousness",
  "flowerily",
  "prosed",
  "redshifts",
  "miscopied",
  "archilowe",
  "eudialyte",
  "reabsorbs",
  "buvette",
  "ostensibilities",
  "rackwork",
  "attritting",
  "acidic",
  "climacterical",
  "blemishments",
  "mycoplasmas",
  "invocates",
  "belaud",
  "prepasted",
  "spleniuses",
  "gam",
  "intercluster",
  "brickwalls",
  "relacquer",
  "outguide",
  "porkwood",
  "defiliations",
  "gangliar",
  "sedgeland",
  "ensorceling",
  "exile",
  "cackles",
  "astonishment",
  "hydrargyrism",
  "bumbag",
  "antiasthmatic",
  "deviancies",
  "panstick",
  "gutsing",
  "hyperpure",
  "overtop",
  "mechanotherapy",
  "enarms",
  "unrule",
  "kiboshes",
  "skeane",
  "ritonavirs",
  "unattentive",
  "redia",
  "reassessments",
  "morphoses",
  "venditations",
  "reformatory",
  "interpersonal",
  "auctions",
  "regalement",
  "dibblers",
  "ephors",
  "aspected",
  "bronchospasms",
  "restack",
  "threadworms",
  "dichotic",
  "spicery",
  "brasilins",
  "oculists",
  "counters",
  "cascadura",
  "kidders",
  "devastations",
  "bastnaesites",
  "apoapsides",
  "blushers",
  "novalia",
  "ascendences",
  "anaemias",
  "unreliability",
  "splendiferously",
  "thymidines",
  "eans",
  "unitarianisms",
  "discomfort",
  "tumour",
  "sentimentalists",
  "mesenchymatous",
  "narrators",
  "lias",
  "deathbeds",
  "muddleheadednesses",
  "napoos",
  "refreshes",
  "bravadoed",
  "examinee",
  "recombinants",
  "oversail",
  "backsey",
  "prefabrication",
  "soaking",
  "unratified",
  "cinematography",
  "lounding",
  "mediatizes",
  "scroungy",
  "castled",
  "tungstens",
  "amylopsin",
  "reverting",
  "nonprescription",
  "qabalas",
  "halt",
  "phaseal",
  "debarcations",
  "decrepitating",
  "pochard",
  "bellpull",
  "innateness",
  "dissocializing",
  "reverent",
  "clonisms",
  "lite",
  "unmeasurable",
  "neocolonialisms",
  "forthcoming",
  "misjoined",
  "miskicks",
  "tulpa",
  "activity",
  "kindrednesses",
  "mesopelagic",
  "stoning",
  "waterpoxes",
  "picnicker",
  "anteaters",
  "angelus",
  "passives",
  "cutlas",
  "electrotonus",
  "pubic",
  "gravitation",
  "trailable",
  "seedness",
  "amalgamates",
  "accinges",
  "porer",
  "forgeries",
  "cully",
  "montaging",
  "fleecie",
  "buntlines",
  "jargonization",
  "exactor",
  "arming",
  "superfluid",
  "undocumented",
  "punkest",
  "vernix",
  "biddings",
  "bonging",
  "congrues",
  "palinode",
  "moxies",
  "whizzings",
  "discerned",
  "shithouse",
  "opacities",
  "link",
  "billycans",
  "hawthorny",
  "kituls",
  "veldskoens",
  "supersedeases",
  "echoier",
  "slots",
  "haberdashers",
  "sugarallies",
  "anniversaries",
  "parchmentized",
  "tamponage",
  "delaminate",
  "sylphidine",
  "unsalvageable",
  "lumbricoid",
  "murmuration",
  "blatt",
  "perfuse",
  "phosphorescent",
  "golps",
  "voyaged",
  "balibuntals",
  "encephalograms",
  "demilitarising",
  "lithemic",
  "yankers",
  "caprifoils",
  "outcrows",
  "merks",
  "menorrhagic",
  "reborn",
  "fallower",
  "busiest",
  "conception",
  "encyclicals",
  "hydroquinones",
  "interpretresses",
  "discontentful",
  "dizenments",
  "legalistic",
  "bichrome",
  "satrapies",
  "calefactory",
  "carroming",
  "entwinement",
  "anemochores",
  "overexercised",
  "heaps",
  "electrooculograms",
  "curry",
  "dimethylnitrosamine",
  "blackwashes",
  "seys",
  "abseilings",
  "freshness",
  "forcedness",
  "animatist",
  "outsummed",
  "vivaciously",
  "platinizing",
  "shockheaded",
  "whore",
  "tooled",
  "loxodromic",
  "jihadist",
  "greenroom",
  "unprovoking",
  "bummalotis",
  "busticate",
  "pillaging",
  "unmistakeably",
  "engluts",
  "ultracompact",
  "polverines",
  "disranked",
  "perichondral",
  "unencouraging",
  "entailed",
  "spinulae",
  "appertinents",
  "rebacked",
  "incusing",
  "catchpoles",
  "uncleanlinesses",
  "alembicated",
  "listel",
  "mappers",
  "addeem",
  "coranachs",
  "sheilings",
  "canoness",
  "unbeaten",
  "redeemers",
  "heady",
  "disentwining",
  "generates",
  "giggly",
  "coherers",
  "photogen",
  "superfusion",
  "patterned",
  "oneyre",
  "votarist",
  "switchings",
  "hallucinogenic",
  "nickelizes",
  "deciares",
  "recocking",
  "fund",
  "kickout",
  "taupe",
  "outstridden",
  "es",
  "imblazes",
  "portraitist",
  "underquotes",
  "rage",
  "phang",
  "trig",
  "pelviform",
  "peni",
  "cybercriminals",
  "couper",
  "araponga",
  "barramundi",
  "cateress",
  "microtomies",
  "bunnias",
  "carsickness",
  "scrimper",
  "deepwaterman",
  "canonises",
  "squattier",
  "vandalisations",
  "handlanger",
  "amygdales",
  "scroggins",
  "mobster",
  "jellification",
  "patriality",
  "opalescently",
  "utterablenesses",
  "epigrammatizing",
  "clewed",
  "saucer",
  "externalizing",
  "campest",
  "grammas",
  "laxism",
  "gurdwara",
  "sises",
  "complices",
  "police",
  "patchboard",
  "divalency",
  "shoogles",
  "momma",
  "footplatemen",
  "sorbable",
  "deliquium",
  "indiscriminating",
  "equisetums",
  "aerosolizing",
  "vivacity",
  "los",
  "neurobiology",
  "roentgenises",
  "itemizations",
  "koel",
  "stroyers",
  "curb",
  "choice",
  "despicableness",
  "electrophysiological",
  "xylic",
  "retextures",
  "lactoflavins",
  "bubu",
  "remaking",
  "unpurchaseable",
  "prescore",
  "drybeat",
  "populars",
  "broomrapes",
  "cutis",
  "slaverers",
  "barograph",
  "pillworms",
  "stateside",
  "silicious",
  "astigmatisms",
  "halakhist",
  "baric",
  "immunoreactions",
  "millinery",
  "asystolic",
  "dinnertime",
  "cartulary",
  "screensaver",
  "impassibleness",
  "bugouts",
  "pinatas",
  "buvette",
  "deoppilates",
  "ottar",
  "intolerablenesses",
  "citranges",
  "underdrive",
  "spankingly",
  "coelomic",
  "enfix",
  "greenish",
  "coater",
  "backhand",
  "instigative",
  "laryngectomy",
  "despiritualizes",
  "dakoitis",
  "stenokies",
  "kab",
  "offerings",
  "bohemian",
  "streetful",
  "justifier",
  "uninitiates",
  "gaelicized",
  "greediness",
  "timbrophilist",
  "oracling",
  "retallies",
  "hobbits",
  "administrative",
  "unaltering",
  "preliminaries",
  "beatifying",
  "histone",
  "concelebrating",
  "decolorisers",
  "cavatine",
  "sunkets",
  "ichthyosaur",
  "golcondas",
  "platycephalous",
  "organists",
  "dewlapt",
  "heminas",
  "professionalization",
  "shantungs",
  "overweenings",
  "leakages",
  "interchanges",
  "grisgris",
  "pillbox",
  "enzymes",
  "cashbox",
  "acajous",
  "rufflier",
  "pergolas",
  "ceilometer",
  "griddlebread",
  "whackers",
  "tornillos",
  "kotukus",
  "mooned",
  "shrank",
  "parasitosis",
  "iconomachy",
  "concrewed",
  "auks",
  "interlooping",
  "dermatites",
  "stamp",
  "unhived",
  "bola",
  "pithinesses",
  "shelfed",
  "patutukis",
  "dipso",
  "gangsterism",
  "isospins",
  "jingoists",
  "twaddly",
  "thermotic",
  "halobiontic",
  "syphilomas",
  "galivant",
  "voiders",
  "rifled",
  "asleep",
  "instating",
  "successor",
  "oxidational",
  "wallfish",
  "inwreathe",
  "ionizing",
  "baldachinos",
  "gigantesque",
  "indigenizes",
  "entomophagous",
  "inevitabilities",
  "saccharized",
  "catty",
  "internucleonic",
  "hagbushes",
  "sidewheel",
  "todger",
  "dinge",
  "nonlibrarians",
  "dietists",
  "presuppositional",
  "essentialized",
  "gladioluses",
  "hovelled",
  "intertropical",
  "synesises",
  "overstayers",
  "explainer",
  "yabbies",
  "asphyxiation",
  "complicate",
  "honorand",
  "crossbow",
  "unionized",
  "puzzling",
  "destructivist",
  "jackmen",
  "styrene",
  "hypnotees",
  "weevil",
  "torc",
  "ditriglyph",
  "freeing",
  "gorged",
  "coplotted",
  "salivated",
  "overfertilise",
  "educatabilities",
  "remarques",
  "mislabeled",
  "demount",
  "voivodeships",
  "chilopodous",
  "perlites",
  "dumbbells",
  "reggaes",
  "birlinns",
  "formular",
  "ophthalmia",
  "possessively",
  "breastsummers",
  "zee",
  "gibes",
  "dout",
  "fandangoes",
  "aeronauts",
  "crystallography",
  "psychogenetic",
  "isle",
  "changeably",
  "rauwolfia",
  "gings",
  "folliculate",
  "aquamanales",
  "unfed",
  "subalternates",
  "supermini",
  "sheetfed",
  "personises",
  "holdbacks",
  "corruptively",
  "hyperbolist",
  "haqueton",
  "wanglers",
  "undershooting",
  "outrivaling",
  "cytomegalic",
  "glitzed",
  "chips",
  "expediential",
  "inimitably",
  "advocator",
  "sustainable",
  "emanation",
  "residuums",
  "greaves",
  "uddered",
  "floridness",
  "cytosol",
  "unpoetical",
  "intentionally",
  "acquisitions",
  "hydrodynamically",
  "lithotripter",
  "respelling",
  "stomachache",
  "checkweighers",
  "brittlest",
  "concerto",
  "begilded",
  "sympathies",
  "wampus",
  "forefronts",
  "flocculus",
  "retaking",
  "inexistent",
  "dovekie",
  "guffawing",
  "nefarious",
  "nonjury",
  "tigridias",
  "validate",
  "feverish",
  "titrated",
  "ubiquinone",
  "lippier",
  "election",
  "bacco",
  "windshake",
  "blastiest",
  "motorcyclings",
  "parolees",
  "protanopia",
  "instrumental",
  "osteogenies",
  "levels",
  "mods",
  "atheizing",
  "insane",
  "gold",
  "cheesiness",
  "peaks",
  "cosmeticize",
  "outfelt",
  "kumbaloi",
  "privateered",
  "porkwoods",
  "bedirty",
  "troke",
  "deepening",
  "historying",
  "cosmopolitanisms",
  "phenylketonuria",
  "staider",
  "gospellers",
  "excommunicable",
  "hoasted",
  "pastedown",
  "incitative",
  "remarkableness",
  "cliffy",
  "neotenic",
  "tweets",
  "chelas",
  "camisado",
  "overtedious",
  "recessionary",
  "overplaid",
  "undemonstrativeness",
  "erythroblasts",
  "salpae",
  "garbagemen",
  "foreshore",
  "matchmarks",
  "argufying",
  "kvetchers",
  "unsphering",
  "annihilatory",
  "vitellin",
  "pinacoids",
  "excogitation",
  "secularities",
  "painstakings",
  "hypnotiser",
  "shutterbug",
  "tardinesses",
  "ethnocentricities",
  "resemblant",
  "stratigraphies",
  "streetwalker",
  "sundaes",
  "penistones",
  "adays",
  "proctal",
  "staunchings",
  "eyeblink",
  "imperious"
];
